### ISSUE TITLE
usage with docker-compose

### ISSUE THREAD

**Issue by opichon** [whilp/ssh-agent#10]
I am trying to use this image in a docker-compose config file without success.

When I try and add a key (ssh-add) I get the following message: `Error connecting to agent: Connection refused`

Here is my docker-compose.yml config:

``` yaml
version: '2'

services:
    ssh-agent:
        image: whilp/ssh-agent:latest
        container_name: ssh-agent
        user: "1001"
        volumes:
            - ssh:/ssh

volumes:
    ssh:
```

``` bash
$ docker run -u 1001 --rm -v ssh:/ssh -v $HOME:$HOME -it whilp/ssh-agent:latest ssh-add $HOME/.ssh/id_rsa
Error connecting to agent: Connection refused
```

**Comment by whilp** [comment]
Hm; when you invoke the `docker run` bit there, have you already started a daemonized container? Can you paste all of the commands you've run (especially `docker-compose`) as well as the output of `docker ps -a`?

**Comment by mrleeio** [comment]
Do you have any example code for docker-compose?

I've been messing around with it for a few hours and I'm a little confused on how to use it across multiple services.

**Comment by opichon** [comment]
My procedure was as follows:
- I start ssh-agent via docker-compose (using the docker-compose.yml file above)
- I run the docker command to add an ssh key (docker command as per docs and as per above)

I don't have the output anymore: since it didn't work, I've switched to running the long-term ssh-agent container directly (i.e. with a docker command as per docs, not via docker-compose).

I suspect the problem with docker-compose has to do with networking. The long-term ssh-agent container is available via the network created by docker-compose, and therefore not directly available anymore. That is about as much as I can tell about Docker networking, unfortunately.

**Comment by djmaze** [comment]
@opichon This is not about Docker networking, but about Docker volumes. You are declaring a named volume called `ssh` inside the compose file. 

Docker Compose automatically namespaces those volumes so they can be accessed from outside the Compose setup through the `<project>_<volume>` convention. The project name by default is inferred from the directory containing your docker-compose.yml. (See [here](https://docs.docker.com/compose/overview/#/multiple-isolated-environments-on-a-single-host) for more information.) 

E.g. if the directory containing your docker-compose.yml is called `ssh-agent`, the project name becomes `sshagent`, and the volume will be called `sshagent_ssh`.

``` bash
$ docker run -u 1001 --rm -v sshagent_ssh:/ssh -v $HOME:$HOME -it whilp/ssh-agent:latest ssh-add $HOME/.ssh/id_rsa
```

Hint: You can find the right volume name using `docker volume ls` as well.

**Comment by pmartens** [comment]
Opichon, Do you have a small example how you fix this issue in your docker-compose file

**Comment by opichon** [comment]
@pmartens I followed the explanations of @djmaze. That works fine. 

In the command to add the ssh key, replace the locale volume with the name of the volume as created by docker-compose. So, instead of `-v ssh:/ssh`, use `-v {local volume name}:/ssh`.

Assuming your `docker-compose.yml` is in directory `my-dir`, and that you've named the volume `ssh` inside the compose config, then the volume name is likely to be `mydir_ssh`.

**Comment by mbrodala** [comment]
FYI this is what I am using right now:

```yaml
  ssh-agent:
    image: whilp/ssh-agent
    command: ssh-add /home/.host/.ssh/id_rsa
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - $HOME:/home/.host
      - ssh-agent:/ssh
```

This launches the SSH agent (as `ENTRYPOINT`) and adds the private key from my host in a single service.

(The `UID` and `GID` can optionally be set via `.env` if you are curious.)
